some changes

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -20,9 +20,11 @@ services:
     command: >
       sh -c "
         echo 'Deleting webhook...';
-        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/deleteWebhook;
-
-        
+        WEBHOOK_STATUS=$$(curl -s -w \"%{http_code}\" -X POST https://api.telegram.org/bot$${TELEGRAM_BOT_TOKEN}/deleteWebhook);
+        if [[ \"$$WEBHOOK_STATUS\" != *\"200\"* ]]; then
+          echo \"Failed to delete webhook. Status: $$WEBHOOK_STATUS\";
+          exit 1;
+        fi;
         # Шаг 1: Ожидание готовности gRPC сервера
         until python3 -c \"import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.settimeout(1); exit(0 if s.connect_ex(('grpc_server', 50051)) == 0 else 1)\"; do
           echo 'Waiting for gRPC server...';
